# Site settings
title: Selanis
author:
  name: Indira Bundavica
  email: your-email@domain.com
description: "Great site about the best natural creams anbd soaps in Bosnia & Herzegowina."

# Build settings
remote_theme: jekyll/minima
